/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.training.pojos.generatedSources;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FlightDataAvroSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6764165272946625825L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FlightDataAvroSchema\",\"namespace\":\"com.training.pojos.generatedSources\",\"fields\":[{\"name\":\"Year\",\"type\":\"long\"},{\"name\":\"Month\",\"type\":\"long\"},{\"name\":\"DayofMonth\",\"type\":\"long\"},{\"name\":\"DayOfWeek\",\"type\":\"long\"},{\"name\":\"DepTime\",\"type\":\"long\"},{\"name\":\"CRSDepTime\",\"type\":\"long\"},{\"name\":\"ArrTime\",\"type\":\"long\"},{\"name\":\"CRSArrTime\",\"type\":\"long\"},{\"name\":\"UniqueCarrier\",\"type\":\"string\"},{\"name\":\"FlightNum\",\"type\":\"long\"},{\"name\":\"TailNum\",\"type\":\"string\"},{\"name\":\"ActualElapsedTime\",\"type\":\"long\"},{\"name\":\"CRSElapsedTime\",\"type\":\"long\"},{\"name\":\"AirTime\",\"type\":\"long\"},{\"name\":\"ArrDelay\",\"type\":\"long\"},{\"name\":\"DepDelay\",\"type\":\"long\"},{\"name\":\"Origin\",\"type\":\"string\"},{\"name\":\"Dest\",\"type\":\"string\"},{\"name\":\"Distance\",\"type\":\"long\"},{\"name\":\"TaxiIn\",\"type\":\"long\"},{\"name\":\"TaxiOut\",\"type\":\"long\"},{\"name\":\"Cancelled\",\"type\":\"long\"},{\"name\":\"CancellationCode\",\"type\":\"string\"},{\"name\":\"Diverted\",\"type\":\"string\"},{\"name\":\"CarrierDelay\",\"type\":\"string\"},{\"name\":\"WeatherDelay\",\"type\":\"string\"},{\"name\":\"NASDelay\",\"type\":\"string\"},{\"name\":\"SecurityDelay\",\"type\":\"string\"},{\"name\":\"LateAircraftDelay\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FlightDataAvroSchema> ENCODER =
      new BinaryMessageEncoder<FlightDataAvroSchema>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FlightDataAvroSchema> DECODER =
      new BinaryMessageDecoder<FlightDataAvroSchema>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<FlightDataAvroSchema> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<FlightDataAvroSchema> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FlightDataAvroSchema>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this FlightDataAvroSchema to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a FlightDataAvroSchema from a ByteBuffer. */
  public static FlightDataAvroSchema fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long Year;
  @Deprecated public long Month;
  @Deprecated public long DayofMonth;
  @Deprecated public long DayOfWeek;
  @Deprecated public long DepTime;
  @Deprecated public long CRSDepTime;
  @Deprecated public long ArrTime;
  @Deprecated public long CRSArrTime;
  @Deprecated public java.lang.CharSequence UniqueCarrier;
  @Deprecated public long FlightNum;
  @Deprecated public java.lang.CharSequence TailNum;
  @Deprecated public long ActualElapsedTime;
  @Deprecated public long CRSElapsedTime;
  @Deprecated public long AirTime;
  @Deprecated public long ArrDelay;
  @Deprecated public long DepDelay;
  @Deprecated public java.lang.CharSequence Origin;
  @Deprecated public java.lang.CharSequence Dest;
  @Deprecated public long Distance;
  @Deprecated public long TaxiIn;
  @Deprecated public long TaxiOut;
  @Deprecated public long Cancelled;
  @Deprecated public java.lang.CharSequence CancellationCode;
  @Deprecated public java.lang.CharSequence Diverted;
  @Deprecated public java.lang.CharSequence CarrierDelay;
  @Deprecated public java.lang.CharSequence WeatherDelay;
  @Deprecated public java.lang.CharSequence NASDelay;
  @Deprecated public java.lang.CharSequence SecurityDelay;
  @Deprecated public java.lang.CharSequence LateAircraftDelay;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FlightDataAvroSchema() {}

  /**
   * All-args constructor.
   * @param Year The new value for Year
   * @param Month The new value for Month
   * @param DayofMonth The new value for DayofMonth
   * @param DayOfWeek The new value for DayOfWeek
   * @param DepTime The new value for DepTime
   * @param CRSDepTime The new value for CRSDepTime
   * @param ArrTime The new value for ArrTime
   * @param CRSArrTime The new value for CRSArrTime
   * @param UniqueCarrier The new value for UniqueCarrier
   * @param FlightNum The new value for FlightNum
   * @param TailNum The new value for TailNum
   * @param ActualElapsedTime The new value for ActualElapsedTime
   * @param CRSElapsedTime The new value for CRSElapsedTime
   * @param AirTime The new value for AirTime
   * @param ArrDelay The new value for ArrDelay
   * @param DepDelay The new value for DepDelay
   * @param Origin The new value for Origin
   * @param Dest The new value for Dest
   * @param Distance The new value for Distance
   * @param TaxiIn The new value for TaxiIn
   * @param TaxiOut The new value for TaxiOut
   * @param Cancelled The new value for Cancelled
   * @param CancellationCode The new value for CancellationCode
   * @param Diverted The new value for Diverted
   * @param CarrierDelay The new value for CarrierDelay
   * @param WeatherDelay The new value for WeatherDelay
   * @param NASDelay The new value for NASDelay
   * @param SecurityDelay The new value for SecurityDelay
   * @param LateAircraftDelay The new value for LateAircraftDelay
   */
  public FlightDataAvroSchema(java.lang.Long Year, java.lang.Long Month, java.lang.Long DayofMonth, java.lang.Long DayOfWeek, java.lang.Long DepTime, java.lang.Long CRSDepTime, java.lang.Long ArrTime, java.lang.Long CRSArrTime, java.lang.CharSequence UniqueCarrier, java.lang.Long FlightNum, java.lang.CharSequence TailNum, java.lang.Long ActualElapsedTime, java.lang.Long CRSElapsedTime, java.lang.Long AirTime, java.lang.Long ArrDelay, java.lang.Long DepDelay, java.lang.CharSequence Origin, java.lang.CharSequence Dest, java.lang.Long Distance, java.lang.Long TaxiIn, java.lang.Long TaxiOut, java.lang.Long Cancelled, java.lang.CharSequence CancellationCode, java.lang.CharSequence Diverted, java.lang.CharSequence CarrierDelay, java.lang.CharSequence WeatherDelay, java.lang.CharSequence NASDelay, java.lang.CharSequence SecurityDelay, java.lang.CharSequence LateAircraftDelay) {
    this.Year = Year;
    this.Month = Month;
    this.DayofMonth = DayofMonth;
    this.DayOfWeek = DayOfWeek;
    this.DepTime = DepTime;
    this.CRSDepTime = CRSDepTime;
    this.ArrTime = ArrTime;
    this.CRSArrTime = CRSArrTime;
    this.UniqueCarrier = UniqueCarrier;
    this.FlightNum = FlightNum;
    this.TailNum = TailNum;
    this.ActualElapsedTime = ActualElapsedTime;
    this.CRSElapsedTime = CRSElapsedTime;
    this.AirTime = AirTime;
    this.ArrDelay = ArrDelay;
    this.DepDelay = DepDelay;
    this.Origin = Origin;
    this.Dest = Dest;
    this.Distance = Distance;
    this.TaxiIn = TaxiIn;
    this.TaxiOut = TaxiOut;
    this.Cancelled = Cancelled;
    this.CancellationCode = CancellationCode;
    this.Diverted = Diverted;
    this.CarrierDelay = CarrierDelay;
    this.WeatherDelay = WeatherDelay;
    this.NASDelay = NASDelay;
    this.SecurityDelay = SecurityDelay;
    this.LateAircraftDelay = LateAircraftDelay;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Year;
    case 1: return Month;
    case 2: return DayofMonth;
    case 3: return DayOfWeek;
    case 4: return DepTime;
    case 5: return CRSDepTime;
    case 6: return ArrTime;
    case 7: return CRSArrTime;
    case 8: return UniqueCarrier;
    case 9: return FlightNum;
    case 10: return TailNum;
    case 11: return ActualElapsedTime;
    case 12: return CRSElapsedTime;
    case 13: return AirTime;
    case 14: return ArrDelay;
    case 15: return DepDelay;
    case 16: return Origin;
    case 17: return Dest;
    case 18: return Distance;
    case 19: return TaxiIn;
    case 20: return TaxiOut;
    case 21: return Cancelled;
    case 22: return CancellationCode;
    case 23: return Diverted;
    case 24: return CarrierDelay;
    case 25: return WeatherDelay;
    case 26: return NASDelay;
    case 27: return SecurityDelay;
    case 28: return LateAircraftDelay;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Year = (java.lang.Long)value$; break;
    case 1: Month = (java.lang.Long)value$; break;
    case 2: DayofMonth = (java.lang.Long)value$; break;
    case 3: DayOfWeek = (java.lang.Long)value$; break;
    case 4: DepTime = (java.lang.Long)value$; break;
    case 5: CRSDepTime = (java.lang.Long)value$; break;
    case 6: ArrTime = (java.lang.Long)value$; break;
    case 7: CRSArrTime = (java.lang.Long)value$; break;
    case 8: UniqueCarrier = (java.lang.CharSequence)value$; break;
    case 9: FlightNum = (java.lang.Long)value$; break;
    case 10: TailNum = (java.lang.CharSequence)value$; break;
    case 11: ActualElapsedTime = (java.lang.Long)value$; break;
    case 12: CRSElapsedTime = (java.lang.Long)value$; break;
    case 13: AirTime = (java.lang.Long)value$; break;
    case 14: ArrDelay = (java.lang.Long)value$; break;
    case 15: DepDelay = (java.lang.Long)value$; break;
    case 16: Origin = (java.lang.CharSequence)value$; break;
    case 17: Dest = (java.lang.CharSequence)value$; break;
    case 18: Distance = (java.lang.Long)value$; break;
    case 19: TaxiIn = (java.lang.Long)value$; break;
    case 20: TaxiOut = (java.lang.Long)value$; break;
    case 21: Cancelled = (java.lang.Long)value$; break;
    case 22: CancellationCode = (java.lang.CharSequence)value$; break;
    case 23: Diverted = (java.lang.CharSequence)value$; break;
    case 24: CarrierDelay = (java.lang.CharSequence)value$; break;
    case 25: WeatherDelay = (java.lang.CharSequence)value$; break;
    case 26: NASDelay = (java.lang.CharSequence)value$; break;
    case 27: SecurityDelay = (java.lang.CharSequence)value$; break;
    case 28: LateAircraftDelay = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Year' field.
   * @return The value of the 'Year' field.
   */
  public java.lang.Long getYear() {
    return Year;
  }

  /**
   * Sets the value of the 'Year' field.
   * @param value the value to set.
   */
  public void setYear(java.lang.Long value) {
    this.Year = value;
  }

  /**
   * Gets the value of the 'Month' field.
   * @return The value of the 'Month' field.
   */
  public java.lang.Long getMonth() {
    return Month;
  }

  /**
   * Sets the value of the 'Month' field.
   * @param value the value to set.
   */
  public void setMonth(java.lang.Long value) {
    this.Month = value;
  }

  /**
   * Gets the value of the 'DayofMonth' field.
   * @return The value of the 'DayofMonth' field.
   */
  public java.lang.Long getDayofMonth() {
    return DayofMonth;
  }

  /**
   * Sets the value of the 'DayofMonth' field.
   * @param value the value to set.
   */
  public void setDayofMonth(java.lang.Long value) {
    this.DayofMonth = value;
  }

  /**
   * Gets the value of the 'DayOfWeek' field.
   * @return The value of the 'DayOfWeek' field.
   */
  public java.lang.Long getDayOfWeek() {
    return DayOfWeek;
  }

  /**
   * Sets the value of the 'DayOfWeek' field.
   * @param value the value to set.
   */
  public void setDayOfWeek(java.lang.Long value) {
    this.DayOfWeek = value;
  }

  /**
   * Gets the value of the 'DepTime' field.
   * @return The value of the 'DepTime' field.
   */
  public java.lang.Long getDepTime() {
    return DepTime;
  }

  /**
   * Sets the value of the 'DepTime' field.
   * @param value the value to set.
   */
  public void setDepTime(java.lang.Long value) {
    this.DepTime = value;
  }

  /**
   * Gets the value of the 'CRSDepTime' field.
   * @return The value of the 'CRSDepTime' field.
   */
  public java.lang.Long getCRSDepTime() {
    return CRSDepTime;
  }

  /**
   * Sets the value of the 'CRSDepTime' field.
   * @param value the value to set.
   */
  public void setCRSDepTime(java.lang.Long value) {
    this.CRSDepTime = value;
  }

  /**
   * Gets the value of the 'ArrTime' field.
   * @return The value of the 'ArrTime' field.
   */
  public java.lang.Long getArrTime() {
    return ArrTime;
  }

  /**
   * Sets the value of the 'ArrTime' field.
   * @param value the value to set.
   */
  public void setArrTime(java.lang.Long value) {
    this.ArrTime = value;
  }

  /**
   * Gets the value of the 'CRSArrTime' field.
   * @return The value of the 'CRSArrTime' field.
   */
  public java.lang.Long getCRSArrTime() {
    return CRSArrTime;
  }

  /**
   * Sets the value of the 'CRSArrTime' field.
   * @param value the value to set.
   */
  public void setCRSArrTime(java.lang.Long value) {
    this.CRSArrTime = value;
  }

  /**
   * Gets the value of the 'UniqueCarrier' field.
   * @return The value of the 'UniqueCarrier' field.
   */
  public java.lang.CharSequence getUniqueCarrier() {
    return UniqueCarrier;
  }

  /**
   * Sets the value of the 'UniqueCarrier' field.
   * @param value the value to set.
   */
  public void setUniqueCarrier(java.lang.CharSequence value) {
    this.UniqueCarrier = value;
  }

  /**
   * Gets the value of the 'FlightNum' field.
   * @return The value of the 'FlightNum' field.
   */
  public java.lang.Long getFlightNum() {
    return FlightNum;
  }

  /**
   * Sets the value of the 'FlightNum' field.
   * @param value the value to set.
   */
  public void setFlightNum(java.lang.Long value) {
    this.FlightNum = value;
  }

  /**
   * Gets the value of the 'TailNum' field.
   * @return The value of the 'TailNum' field.
   */
  public java.lang.CharSequence getTailNum() {
    return TailNum;
  }

  /**
   * Sets the value of the 'TailNum' field.
   * @param value the value to set.
   */
  public void setTailNum(java.lang.CharSequence value) {
    this.TailNum = value;
  }

  /**
   * Gets the value of the 'ActualElapsedTime' field.
   * @return The value of the 'ActualElapsedTime' field.
   */
  public java.lang.Long getActualElapsedTime() {
    return ActualElapsedTime;
  }

  /**
   * Sets the value of the 'ActualElapsedTime' field.
   * @param value the value to set.
   */
  public void setActualElapsedTime(java.lang.Long value) {
    this.ActualElapsedTime = value;
  }

  /**
   * Gets the value of the 'CRSElapsedTime' field.
   * @return The value of the 'CRSElapsedTime' field.
   */
  public java.lang.Long getCRSElapsedTime() {
    return CRSElapsedTime;
  }

  /**
   * Sets the value of the 'CRSElapsedTime' field.
   * @param value the value to set.
   */
  public void setCRSElapsedTime(java.lang.Long value) {
    this.CRSElapsedTime = value;
  }

  /**
   * Gets the value of the 'AirTime' field.
   * @return The value of the 'AirTime' field.
   */
  public java.lang.Long getAirTime() {
    return AirTime;
  }

  /**
   * Sets the value of the 'AirTime' field.
   * @param value the value to set.
   */
  public void setAirTime(java.lang.Long value) {
    this.AirTime = value;
  }

  /**
   * Gets the value of the 'ArrDelay' field.
   * @return The value of the 'ArrDelay' field.
   */
  public java.lang.Long getArrDelay() {
    return ArrDelay;
  }

  /**
   * Sets the value of the 'ArrDelay' field.
   * @param value the value to set.
   */
  public void setArrDelay(java.lang.Long value) {
    this.ArrDelay = value;
  }

  /**
   * Gets the value of the 'DepDelay' field.
   * @return The value of the 'DepDelay' field.
   */
  public java.lang.Long getDepDelay() {
    return DepDelay;
  }

  /**
   * Sets the value of the 'DepDelay' field.
   * @param value the value to set.
   */
  public void setDepDelay(java.lang.Long value) {
    this.DepDelay = value;
  }

  /**
   * Gets the value of the 'Origin' field.
   * @return The value of the 'Origin' field.
   */
  public java.lang.CharSequence getOrigin() {
    return Origin;
  }

  /**
   * Sets the value of the 'Origin' field.
   * @param value the value to set.
   */
  public void setOrigin(java.lang.CharSequence value) {
    this.Origin = value;
  }

  /**
   * Gets the value of the 'Dest' field.
   * @return The value of the 'Dest' field.
   */
  public java.lang.CharSequence getDest() {
    return Dest;
  }

  /**
   * Sets the value of the 'Dest' field.
   * @param value the value to set.
   */
  public void setDest(java.lang.CharSequence value) {
    this.Dest = value;
  }

  /**
   * Gets the value of the 'Distance' field.
   * @return The value of the 'Distance' field.
   */
  public java.lang.Long getDistance() {
    return Distance;
  }

  /**
   * Sets the value of the 'Distance' field.
   * @param value the value to set.
   */
  public void setDistance(java.lang.Long value) {
    this.Distance = value;
  }

  /**
   * Gets the value of the 'TaxiIn' field.
   * @return The value of the 'TaxiIn' field.
   */
  public java.lang.Long getTaxiIn() {
    return TaxiIn;
  }

  /**
   * Sets the value of the 'TaxiIn' field.
   * @param value the value to set.
   */
  public void setTaxiIn(java.lang.Long value) {
    this.TaxiIn = value;
  }

  /**
   * Gets the value of the 'TaxiOut' field.
   * @return The value of the 'TaxiOut' field.
   */
  public java.lang.Long getTaxiOut() {
    return TaxiOut;
  }

  /**
   * Sets the value of the 'TaxiOut' field.
   * @param value the value to set.
   */
  public void setTaxiOut(java.lang.Long value) {
    this.TaxiOut = value;
  }

  /**
   * Gets the value of the 'Cancelled' field.
   * @return The value of the 'Cancelled' field.
   */
  public java.lang.Long getCancelled() {
    return Cancelled;
  }

  /**
   * Sets the value of the 'Cancelled' field.
   * @param value the value to set.
   */
  public void setCancelled(java.lang.Long value) {
    this.Cancelled = value;
  }

  /**
   * Gets the value of the 'CancellationCode' field.
   * @return The value of the 'CancellationCode' field.
   */
  public java.lang.CharSequence getCancellationCode() {
    return CancellationCode;
  }

  /**
   * Sets the value of the 'CancellationCode' field.
   * @param value the value to set.
   */
  public void setCancellationCode(java.lang.CharSequence value) {
    this.CancellationCode = value;
  }

  /**
   * Gets the value of the 'Diverted' field.
   * @return The value of the 'Diverted' field.
   */
  public java.lang.CharSequence getDiverted() {
    return Diverted;
  }

  /**
   * Sets the value of the 'Diverted' field.
   * @param value the value to set.
   */
  public void setDiverted(java.lang.CharSequence value) {
    this.Diverted = value;
  }

  /**
   * Gets the value of the 'CarrierDelay' field.
   * @return The value of the 'CarrierDelay' field.
   */
  public java.lang.CharSequence getCarrierDelay() {
    return CarrierDelay;
  }

  /**
   * Sets the value of the 'CarrierDelay' field.
   * @param value the value to set.
   */
  public void setCarrierDelay(java.lang.CharSequence value) {
    this.CarrierDelay = value;
  }

  /**
   * Gets the value of the 'WeatherDelay' field.
   * @return The value of the 'WeatherDelay' field.
   */
  public java.lang.CharSequence getWeatherDelay() {
    return WeatherDelay;
  }

  /**
   * Sets the value of the 'WeatherDelay' field.
   * @param value the value to set.
   */
  public void setWeatherDelay(java.lang.CharSequence value) {
    this.WeatherDelay = value;
  }

  /**
   * Gets the value of the 'NASDelay' field.
   * @return The value of the 'NASDelay' field.
   */
  public java.lang.CharSequence getNASDelay() {
    return NASDelay;
  }

  /**
   * Sets the value of the 'NASDelay' field.
   * @param value the value to set.
   */
  public void setNASDelay(java.lang.CharSequence value) {
    this.NASDelay = value;
  }

  /**
   * Gets the value of the 'SecurityDelay' field.
   * @return The value of the 'SecurityDelay' field.
   */
  public java.lang.CharSequence getSecurityDelay() {
    return SecurityDelay;
  }

  /**
   * Sets the value of the 'SecurityDelay' field.
   * @param value the value to set.
   */
  public void setSecurityDelay(java.lang.CharSequence value) {
    this.SecurityDelay = value;
  }

  /**
   * Gets the value of the 'LateAircraftDelay' field.
   * @return The value of the 'LateAircraftDelay' field.
   */
  public java.lang.CharSequence getLateAircraftDelay() {
    return LateAircraftDelay;
  }

  /**
   * Sets the value of the 'LateAircraftDelay' field.
   * @param value the value to set.
   */
  public void setLateAircraftDelay(java.lang.CharSequence value) {
    this.LateAircraftDelay = value;
  }

  /**
   * Creates a new FlightDataAvroSchema RecordBuilder.
   * @return A new FlightDataAvroSchema RecordBuilder
   */
  public static com.training.pojos.generatedSources.FlightDataAvroSchema.Builder newBuilder() {
    return new com.training.pojos.generatedSources.FlightDataAvroSchema.Builder();
  }

  /**
   * Creates a new FlightDataAvroSchema RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FlightDataAvroSchema RecordBuilder
   */
  public static com.training.pojos.generatedSources.FlightDataAvroSchema.Builder newBuilder(com.training.pojos.generatedSources.FlightDataAvroSchema.Builder other) {
    return new com.training.pojos.generatedSources.FlightDataAvroSchema.Builder(other);
  }

  /**
   * Creates a new FlightDataAvroSchema RecordBuilder by copying an existing FlightDataAvroSchema instance.
   * @param other The existing instance to copy.
   * @return A new FlightDataAvroSchema RecordBuilder
   */
  public static com.training.pojos.generatedSources.FlightDataAvroSchema.Builder newBuilder(com.training.pojos.generatedSources.FlightDataAvroSchema other) {
    return new com.training.pojos.generatedSources.FlightDataAvroSchema.Builder(other);
  }

  /**
   * RecordBuilder for FlightDataAvroSchema instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FlightDataAvroSchema>
    implements org.apache.avro.data.RecordBuilder<FlightDataAvroSchema> {

    private long Year;
    private long Month;
    private long DayofMonth;
    private long DayOfWeek;
    private long DepTime;
    private long CRSDepTime;
    private long ArrTime;
    private long CRSArrTime;
    private java.lang.CharSequence UniqueCarrier;
    private long FlightNum;
    private java.lang.CharSequence TailNum;
    private long ActualElapsedTime;
    private long CRSElapsedTime;
    private long AirTime;
    private long ArrDelay;
    private long DepDelay;
    private java.lang.CharSequence Origin;
    private java.lang.CharSequence Dest;
    private long Distance;
    private long TaxiIn;
    private long TaxiOut;
    private long Cancelled;
    private java.lang.CharSequence CancellationCode;
    private java.lang.CharSequence Diverted;
    private java.lang.CharSequence CarrierDelay;
    private java.lang.CharSequence WeatherDelay;
    private java.lang.CharSequence NASDelay;
    private java.lang.CharSequence SecurityDelay;
    private java.lang.CharSequence LateAircraftDelay;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.training.pojos.generatedSources.FlightDataAvroSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Year)) {
        this.Year = data().deepCopy(fields()[0].schema(), other.Year);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Month)) {
        this.Month = data().deepCopy(fields()[1].schema(), other.Month);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.DayofMonth)) {
        this.DayofMonth = data().deepCopy(fields()[2].schema(), other.DayofMonth);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.DayOfWeek)) {
        this.DayOfWeek = data().deepCopy(fields()[3].schema(), other.DayOfWeek);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.DepTime)) {
        this.DepTime = data().deepCopy(fields()[4].schema(), other.DepTime);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.CRSDepTime)) {
        this.CRSDepTime = data().deepCopy(fields()[5].schema(), other.CRSDepTime);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.ArrTime)) {
        this.ArrTime = data().deepCopy(fields()[6].schema(), other.ArrTime);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.CRSArrTime)) {
        this.CRSArrTime = data().deepCopy(fields()[7].schema(), other.CRSArrTime);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.UniqueCarrier)) {
        this.UniqueCarrier = data().deepCopy(fields()[8].schema(), other.UniqueCarrier);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.FlightNum)) {
        this.FlightNum = data().deepCopy(fields()[9].schema(), other.FlightNum);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.TailNum)) {
        this.TailNum = data().deepCopy(fields()[10].schema(), other.TailNum);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.ActualElapsedTime)) {
        this.ActualElapsedTime = data().deepCopy(fields()[11].schema(), other.ActualElapsedTime);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.CRSElapsedTime)) {
        this.CRSElapsedTime = data().deepCopy(fields()[12].schema(), other.CRSElapsedTime);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.AirTime)) {
        this.AirTime = data().deepCopy(fields()[13].schema(), other.AirTime);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.ArrDelay)) {
        this.ArrDelay = data().deepCopy(fields()[14].schema(), other.ArrDelay);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.DepDelay)) {
        this.DepDelay = data().deepCopy(fields()[15].schema(), other.DepDelay);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.Origin)) {
        this.Origin = data().deepCopy(fields()[16].schema(), other.Origin);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.Dest)) {
        this.Dest = data().deepCopy(fields()[17].schema(), other.Dest);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.Distance)) {
        this.Distance = data().deepCopy(fields()[18].schema(), other.Distance);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.TaxiIn)) {
        this.TaxiIn = data().deepCopy(fields()[19].schema(), other.TaxiIn);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.TaxiOut)) {
        this.TaxiOut = data().deepCopy(fields()[20].schema(), other.TaxiOut);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.Cancelled)) {
        this.Cancelled = data().deepCopy(fields()[21].schema(), other.Cancelled);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.CancellationCode)) {
        this.CancellationCode = data().deepCopy(fields()[22].schema(), other.CancellationCode);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.Diverted)) {
        this.Diverted = data().deepCopy(fields()[23].schema(), other.Diverted);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.CarrierDelay)) {
        this.CarrierDelay = data().deepCopy(fields()[24].schema(), other.CarrierDelay);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.WeatherDelay)) {
        this.WeatherDelay = data().deepCopy(fields()[25].schema(), other.WeatherDelay);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.NASDelay)) {
        this.NASDelay = data().deepCopy(fields()[26].schema(), other.NASDelay);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.SecurityDelay)) {
        this.SecurityDelay = data().deepCopy(fields()[27].schema(), other.SecurityDelay);
        fieldSetFlags()[27] = true;
      }
      if (isValidValue(fields()[28], other.LateAircraftDelay)) {
        this.LateAircraftDelay = data().deepCopy(fields()[28].schema(), other.LateAircraftDelay);
        fieldSetFlags()[28] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing FlightDataAvroSchema instance
     * @param other The existing instance to copy.
     */
    private Builder(com.training.pojos.generatedSources.FlightDataAvroSchema other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.Year)) {
        this.Year = data().deepCopy(fields()[0].schema(), other.Year);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Month)) {
        this.Month = data().deepCopy(fields()[1].schema(), other.Month);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.DayofMonth)) {
        this.DayofMonth = data().deepCopy(fields()[2].schema(), other.DayofMonth);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.DayOfWeek)) {
        this.DayOfWeek = data().deepCopy(fields()[3].schema(), other.DayOfWeek);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.DepTime)) {
        this.DepTime = data().deepCopy(fields()[4].schema(), other.DepTime);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.CRSDepTime)) {
        this.CRSDepTime = data().deepCopy(fields()[5].schema(), other.CRSDepTime);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.ArrTime)) {
        this.ArrTime = data().deepCopy(fields()[6].schema(), other.ArrTime);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.CRSArrTime)) {
        this.CRSArrTime = data().deepCopy(fields()[7].schema(), other.CRSArrTime);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.UniqueCarrier)) {
        this.UniqueCarrier = data().deepCopy(fields()[8].schema(), other.UniqueCarrier);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.FlightNum)) {
        this.FlightNum = data().deepCopy(fields()[9].schema(), other.FlightNum);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.TailNum)) {
        this.TailNum = data().deepCopy(fields()[10].schema(), other.TailNum);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.ActualElapsedTime)) {
        this.ActualElapsedTime = data().deepCopy(fields()[11].schema(), other.ActualElapsedTime);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.CRSElapsedTime)) {
        this.CRSElapsedTime = data().deepCopy(fields()[12].schema(), other.CRSElapsedTime);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.AirTime)) {
        this.AirTime = data().deepCopy(fields()[13].schema(), other.AirTime);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.ArrDelay)) {
        this.ArrDelay = data().deepCopy(fields()[14].schema(), other.ArrDelay);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.DepDelay)) {
        this.DepDelay = data().deepCopy(fields()[15].schema(), other.DepDelay);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.Origin)) {
        this.Origin = data().deepCopy(fields()[16].schema(), other.Origin);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.Dest)) {
        this.Dest = data().deepCopy(fields()[17].schema(), other.Dest);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.Distance)) {
        this.Distance = data().deepCopy(fields()[18].schema(), other.Distance);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.TaxiIn)) {
        this.TaxiIn = data().deepCopy(fields()[19].schema(), other.TaxiIn);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.TaxiOut)) {
        this.TaxiOut = data().deepCopy(fields()[20].schema(), other.TaxiOut);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.Cancelled)) {
        this.Cancelled = data().deepCopy(fields()[21].schema(), other.Cancelled);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.CancellationCode)) {
        this.CancellationCode = data().deepCopy(fields()[22].schema(), other.CancellationCode);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.Diverted)) {
        this.Diverted = data().deepCopy(fields()[23].schema(), other.Diverted);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.CarrierDelay)) {
        this.CarrierDelay = data().deepCopy(fields()[24].schema(), other.CarrierDelay);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.WeatherDelay)) {
        this.WeatherDelay = data().deepCopy(fields()[25].schema(), other.WeatherDelay);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.NASDelay)) {
        this.NASDelay = data().deepCopy(fields()[26].schema(), other.NASDelay);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.SecurityDelay)) {
        this.SecurityDelay = data().deepCopy(fields()[27].schema(), other.SecurityDelay);
        fieldSetFlags()[27] = true;
      }
      if (isValidValue(fields()[28], other.LateAircraftDelay)) {
        this.LateAircraftDelay = data().deepCopy(fields()[28].schema(), other.LateAircraftDelay);
        fieldSetFlags()[28] = true;
      }
    }

    /**
      * Gets the value of the 'Year' field.
      * @return The value.
      */
    public java.lang.Long getYear() {
      return Year;
    }

    /**
      * Sets the value of the 'Year' field.
      * @param value The value of 'Year'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setYear(long value) {
      validate(fields()[0], value);
      this.Year = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Year' field has been set.
      * @return True if the 'Year' field has been set, false otherwise.
      */
    public boolean hasYear() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Year' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearYear() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Month' field.
      * @return The value.
      */
    public java.lang.Long getMonth() {
      return Month;
    }

    /**
      * Sets the value of the 'Month' field.
      * @param value The value of 'Month'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setMonth(long value) {
      validate(fields()[1], value);
      this.Month = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Month' field has been set.
      * @return True if the 'Month' field has been set, false otherwise.
      */
    public boolean hasMonth() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Month' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearMonth() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'DayofMonth' field.
      * @return The value.
      */
    public java.lang.Long getDayofMonth() {
      return DayofMonth;
    }

    /**
      * Sets the value of the 'DayofMonth' field.
      * @param value The value of 'DayofMonth'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setDayofMonth(long value) {
      validate(fields()[2], value);
      this.DayofMonth = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'DayofMonth' field has been set.
      * @return True if the 'DayofMonth' field has been set, false otherwise.
      */
    public boolean hasDayofMonth() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'DayofMonth' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearDayofMonth() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'DayOfWeek' field.
      * @return The value.
      */
    public java.lang.Long getDayOfWeek() {
      return DayOfWeek;
    }

    /**
      * Sets the value of the 'DayOfWeek' field.
      * @param value The value of 'DayOfWeek'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setDayOfWeek(long value) {
      validate(fields()[3], value);
      this.DayOfWeek = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'DayOfWeek' field has been set.
      * @return True if the 'DayOfWeek' field has been set, false otherwise.
      */
    public boolean hasDayOfWeek() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'DayOfWeek' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearDayOfWeek() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'DepTime' field.
      * @return The value.
      */
    public java.lang.Long getDepTime() {
      return DepTime;
    }

    /**
      * Sets the value of the 'DepTime' field.
      * @param value The value of 'DepTime'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setDepTime(long value) {
      validate(fields()[4], value);
      this.DepTime = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'DepTime' field has been set.
      * @return True if the 'DepTime' field has been set, false otherwise.
      */
    public boolean hasDepTime() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'DepTime' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearDepTime() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'CRSDepTime' field.
      * @return The value.
      */
    public java.lang.Long getCRSDepTime() {
      return CRSDepTime;
    }

    /**
      * Sets the value of the 'CRSDepTime' field.
      * @param value The value of 'CRSDepTime'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setCRSDepTime(long value) {
      validate(fields()[5], value);
      this.CRSDepTime = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'CRSDepTime' field has been set.
      * @return True if the 'CRSDepTime' field has been set, false otherwise.
      */
    public boolean hasCRSDepTime() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'CRSDepTime' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearCRSDepTime() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'ArrTime' field.
      * @return The value.
      */
    public java.lang.Long getArrTime() {
      return ArrTime;
    }

    /**
      * Sets the value of the 'ArrTime' field.
      * @param value The value of 'ArrTime'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setArrTime(long value) {
      validate(fields()[6], value);
      this.ArrTime = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'ArrTime' field has been set.
      * @return True if the 'ArrTime' field has been set, false otherwise.
      */
    public boolean hasArrTime() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'ArrTime' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearArrTime() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'CRSArrTime' field.
      * @return The value.
      */
    public java.lang.Long getCRSArrTime() {
      return CRSArrTime;
    }

    /**
      * Sets the value of the 'CRSArrTime' field.
      * @param value The value of 'CRSArrTime'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setCRSArrTime(long value) {
      validate(fields()[7], value);
      this.CRSArrTime = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'CRSArrTime' field has been set.
      * @return True if the 'CRSArrTime' field has been set, false otherwise.
      */
    public boolean hasCRSArrTime() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'CRSArrTime' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearCRSArrTime() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'UniqueCarrier' field.
      * @return The value.
      */
    public java.lang.CharSequence getUniqueCarrier() {
      return UniqueCarrier;
    }

    /**
      * Sets the value of the 'UniqueCarrier' field.
      * @param value The value of 'UniqueCarrier'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setUniqueCarrier(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.UniqueCarrier = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'UniqueCarrier' field has been set.
      * @return True if the 'UniqueCarrier' field has been set, false otherwise.
      */
    public boolean hasUniqueCarrier() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'UniqueCarrier' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearUniqueCarrier() {
      UniqueCarrier = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'FlightNum' field.
      * @return The value.
      */
    public java.lang.Long getFlightNum() {
      return FlightNum;
    }

    /**
      * Sets the value of the 'FlightNum' field.
      * @param value The value of 'FlightNum'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setFlightNum(long value) {
      validate(fields()[9], value);
      this.FlightNum = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'FlightNum' field has been set.
      * @return True if the 'FlightNum' field has been set, false otherwise.
      */
    public boolean hasFlightNum() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'FlightNum' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearFlightNum() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'TailNum' field.
      * @return The value.
      */
    public java.lang.CharSequence getTailNum() {
      return TailNum;
    }

    /**
      * Sets the value of the 'TailNum' field.
      * @param value The value of 'TailNum'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setTailNum(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.TailNum = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'TailNum' field has been set.
      * @return True if the 'TailNum' field has been set, false otherwise.
      */
    public boolean hasTailNum() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'TailNum' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearTailNum() {
      TailNum = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'ActualElapsedTime' field.
      * @return The value.
      */
    public java.lang.Long getActualElapsedTime() {
      return ActualElapsedTime;
    }

    /**
      * Sets the value of the 'ActualElapsedTime' field.
      * @param value The value of 'ActualElapsedTime'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setActualElapsedTime(long value) {
      validate(fields()[11], value);
      this.ActualElapsedTime = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'ActualElapsedTime' field has been set.
      * @return True if the 'ActualElapsedTime' field has been set, false otherwise.
      */
    public boolean hasActualElapsedTime() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'ActualElapsedTime' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearActualElapsedTime() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'CRSElapsedTime' field.
      * @return The value.
      */
    public java.lang.Long getCRSElapsedTime() {
      return CRSElapsedTime;
    }

    /**
      * Sets the value of the 'CRSElapsedTime' field.
      * @param value The value of 'CRSElapsedTime'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setCRSElapsedTime(long value) {
      validate(fields()[12], value);
      this.CRSElapsedTime = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'CRSElapsedTime' field has been set.
      * @return True if the 'CRSElapsedTime' field has been set, false otherwise.
      */
    public boolean hasCRSElapsedTime() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'CRSElapsedTime' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearCRSElapsedTime() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'AirTime' field.
      * @return The value.
      */
    public java.lang.Long getAirTime() {
      return AirTime;
    }

    /**
      * Sets the value of the 'AirTime' field.
      * @param value The value of 'AirTime'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setAirTime(long value) {
      validate(fields()[13], value);
      this.AirTime = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'AirTime' field has been set.
      * @return True if the 'AirTime' field has been set, false otherwise.
      */
    public boolean hasAirTime() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'AirTime' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearAirTime() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'ArrDelay' field.
      * @return The value.
      */
    public java.lang.Long getArrDelay() {
      return ArrDelay;
    }

    /**
      * Sets the value of the 'ArrDelay' field.
      * @param value The value of 'ArrDelay'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setArrDelay(long value) {
      validate(fields()[14], value);
      this.ArrDelay = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'ArrDelay' field has been set.
      * @return True if the 'ArrDelay' field has been set, false otherwise.
      */
    public boolean hasArrDelay() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'ArrDelay' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearArrDelay() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'DepDelay' field.
      * @return The value.
      */
    public java.lang.Long getDepDelay() {
      return DepDelay;
    }

    /**
      * Sets the value of the 'DepDelay' field.
      * @param value The value of 'DepDelay'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setDepDelay(long value) {
      validate(fields()[15], value);
      this.DepDelay = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'DepDelay' field has been set.
      * @return True if the 'DepDelay' field has been set, false otherwise.
      */
    public boolean hasDepDelay() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'DepDelay' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearDepDelay() {
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'Origin' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrigin() {
      return Origin;
    }

    /**
      * Sets the value of the 'Origin' field.
      * @param value The value of 'Origin'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setOrigin(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.Origin = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'Origin' field has been set.
      * @return True if the 'Origin' field has been set, false otherwise.
      */
    public boolean hasOrigin() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'Origin' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearOrigin() {
      Origin = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'Dest' field.
      * @return The value.
      */
    public java.lang.CharSequence getDest() {
      return Dest;
    }

    /**
      * Sets the value of the 'Dest' field.
      * @param value The value of 'Dest'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setDest(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.Dest = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'Dest' field has been set.
      * @return True if the 'Dest' field has been set, false otherwise.
      */
    public boolean hasDest() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'Dest' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearDest() {
      Dest = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'Distance' field.
      * @return The value.
      */
    public java.lang.Long getDistance() {
      return Distance;
    }

    /**
      * Sets the value of the 'Distance' field.
      * @param value The value of 'Distance'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setDistance(long value) {
      validate(fields()[18], value);
      this.Distance = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'Distance' field has been set.
      * @return True if the 'Distance' field has been set, false otherwise.
      */
    public boolean hasDistance() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'Distance' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearDistance() {
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'TaxiIn' field.
      * @return The value.
      */
    public java.lang.Long getTaxiIn() {
      return TaxiIn;
    }

    /**
      * Sets the value of the 'TaxiIn' field.
      * @param value The value of 'TaxiIn'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setTaxiIn(long value) {
      validate(fields()[19], value);
      this.TaxiIn = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'TaxiIn' field has been set.
      * @return True if the 'TaxiIn' field has been set, false otherwise.
      */
    public boolean hasTaxiIn() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'TaxiIn' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearTaxiIn() {
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'TaxiOut' field.
      * @return The value.
      */
    public java.lang.Long getTaxiOut() {
      return TaxiOut;
    }

    /**
      * Sets the value of the 'TaxiOut' field.
      * @param value The value of 'TaxiOut'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setTaxiOut(long value) {
      validate(fields()[20], value);
      this.TaxiOut = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'TaxiOut' field has been set.
      * @return True if the 'TaxiOut' field has been set, false otherwise.
      */
    public boolean hasTaxiOut() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'TaxiOut' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearTaxiOut() {
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'Cancelled' field.
      * @return The value.
      */
    public java.lang.Long getCancelled() {
      return Cancelled;
    }

    /**
      * Sets the value of the 'Cancelled' field.
      * @param value The value of 'Cancelled'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setCancelled(long value) {
      validate(fields()[21], value);
      this.Cancelled = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'Cancelled' field has been set.
      * @return True if the 'Cancelled' field has been set, false otherwise.
      */
    public boolean hasCancelled() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'Cancelled' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearCancelled() {
      fieldSetFlags()[21] = false;
      return this;
    }

    /**
      * Gets the value of the 'CancellationCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getCancellationCode() {
      return CancellationCode;
    }

    /**
      * Sets the value of the 'CancellationCode' field.
      * @param value The value of 'CancellationCode'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setCancellationCode(java.lang.CharSequence value) {
      validate(fields()[22], value);
      this.CancellationCode = value;
      fieldSetFlags()[22] = true;
      return this;
    }

    /**
      * Checks whether the 'CancellationCode' field has been set.
      * @return True if the 'CancellationCode' field has been set, false otherwise.
      */
    public boolean hasCancellationCode() {
      return fieldSetFlags()[22];
    }


    /**
      * Clears the value of the 'CancellationCode' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearCancellationCode() {
      CancellationCode = null;
      fieldSetFlags()[22] = false;
      return this;
    }

    /**
      * Gets the value of the 'Diverted' field.
      * @return The value.
      */
    public java.lang.CharSequence getDiverted() {
      return Diverted;
    }

    /**
      * Sets the value of the 'Diverted' field.
      * @param value The value of 'Diverted'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setDiverted(java.lang.CharSequence value) {
      validate(fields()[23], value);
      this.Diverted = value;
      fieldSetFlags()[23] = true;
      return this;
    }

    /**
      * Checks whether the 'Diverted' field has been set.
      * @return True if the 'Diverted' field has been set, false otherwise.
      */
    public boolean hasDiverted() {
      return fieldSetFlags()[23];
    }


    /**
      * Clears the value of the 'Diverted' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearDiverted() {
      Diverted = null;
      fieldSetFlags()[23] = false;
      return this;
    }

    /**
      * Gets the value of the 'CarrierDelay' field.
      * @return The value.
      */
    public java.lang.CharSequence getCarrierDelay() {
      return CarrierDelay;
    }

    /**
      * Sets the value of the 'CarrierDelay' field.
      * @param value The value of 'CarrierDelay'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setCarrierDelay(java.lang.CharSequence value) {
      validate(fields()[24], value);
      this.CarrierDelay = value;
      fieldSetFlags()[24] = true;
      return this;
    }

    /**
      * Checks whether the 'CarrierDelay' field has been set.
      * @return True if the 'CarrierDelay' field has been set, false otherwise.
      */
    public boolean hasCarrierDelay() {
      return fieldSetFlags()[24];
    }


    /**
      * Clears the value of the 'CarrierDelay' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearCarrierDelay() {
      CarrierDelay = null;
      fieldSetFlags()[24] = false;
      return this;
    }

    /**
      * Gets the value of the 'WeatherDelay' field.
      * @return The value.
      */
    public java.lang.CharSequence getWeatherDelay() {
      return WeatherDelay;
    }

    /**
      * Sets the value of the 'WeatherDelay' field.
      * @param value The value of 'WeatherDelay'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setWeatherDelay(java.lang.CharSequence value) {
      validate(fields()[25], value);
      this.WeatherDelay = value;
      fieldSetFlags()[25] = true;
      return this;
    }

    /**
      * Checks whether the 'WeatherDelay' field has been set.
      * @return True if the 'WeatherDelay' field has been set, false otherwise.
      */
    public boolean hasWeatherDelay() {
      return fieldSetFlags()[25];
    }


    /**
      * Clears the value of the 'WeatherDelay' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearWeatherDelay() {
      WeatherDelay = null;
      fieldSetFlags()[25] = false;
      return this;
    }

    /**
      * Gets the value of the 'NASDelay' field.
      * @return The value.
      */
    public java.lang.CharSequence getNASDelay() {
      return NASDelay;
    }

    /**
      * Sets the value of the 'NASDelay' field.
      * @param value The value of 'NASDelay'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setNASDelay(java.lang.CharSequence value) {
      validate(fields()[26], value);
      this.NASDelay = value;
      fieldSetFlags()[26] = true;
      return this;
    }

    /**
      * Checks whether the 'NASDelay' field has been set.
      * @return True if the 'NASDelay' field has been set, false otherwise.
      */
    public boolean hasNASDelay() {
      return fieldSetFlags()[26];
    }


    /**
      * Clears the value of the 'NASDelay' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearNASDelay() {
      NASDelay = null;
      fieldSetFlags()[26] = false;
      return this;
    }

    /**
      * Gets the value of the 'SecurityDelay' field.
      * @return The value.
      */
    public java.lang.CharSequence getSecurityDelay() {
      return SecurityDelay;
    }

    /**
      * Sets the value of the 'SecurityDelay' field.
      * @param value The value of 'SecurityDelay'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setSecurityDelay(java.lang.CharSequence value) {
      validate(fields()[27], value);
      this.SecurityDelay = value;
      fieldSetFlags()[27] = true;
      return this;
    }

    /**
      * Checks whether the 'SecurityDelay' field has been set.
      * @return True if the 'SecurityDelay' field has been set, false otherwise.
      */
    public boolean hasSecurityDelay() {
      return fieldSetFlags()[27];
    }


    /**
      * Clears the value of the 'SecurityDelay' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearSecurityDelay() {
      SecurityDelay = null;
      fieldSetFlags()[27] = false;
      return this;
    }

    /**
      * Gets the value of the 'LateAircraftDelay' field.
      * @return The value.
      */
    public java.lang.CharSequence getLateAircraftDelay() {
      return LateAircraftDelay;
    }

    /**
      * Sets the value of the 'LateAircraftDelay' field.
      * @param value The value of 'LateAircraftDelay'.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder setLateAircraftDelay(java.lang.CharSequence value) {
      validate(fields()[28], value);
      this.LateAircraftDelay = value;
      fieldSetFlags()[28] = true;
      return this;
    }

    /**
      * Checks whether the 'LateAircraftDelay' field has been set.
      * @return True if the 'LateAircraftDelay' field has been set, false otherwise.
      */
    public boolean hasLateAircraftDelay() {
      return fieldSetFlags()[28];
    }


    /**
      * Clears the value of the 'LateAircraftDelay' field.
      * @return This builder.
      */
    public com.training.pojos.generatedSources.FlightDataAvroSchema.Builder clearLateAircraftDelay() {
      LateAircraftDelay = null;
      fieldSetFlags()[28] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FlightDataAvroSchema build() {
      try {
        FlightDataAvroSchema record = new FlightDataAvroSchema();
        record.Year = fieldSetFlags()[0] ? this.Year : (java.lang.Long) defaultValue(fields()[0]);
        record.Month = fieldSetFlags()[1] ? this.Month : (java.lang.Long) defaultValue(fields()[1]);
        record.DayofMonth = fieldSetFlags()[2] ? this.DayofMonth : (java.lang.Long) defaultValue(fields()[2]);
        record.DayOfWeek = fieldSetFlags()[3] ? this.DayOfWeek : (java.lang.Long) defaultValue(fields()[3]);
        record.DepTime = fieldSetFlags()[4] ? this.DepTime : (java.lang.Long) defaultValue(fields()[4]);
        record.CRSDepTime = fieldSetFlags()[5] ? this.CRSDepTime : (java.lang.Long) defaultValue(fields()[5]);
        record.ArrTime = fieldSetFlags()[6] ? this.ArrTime : (java.lang.Long) defaultValue(fields()[6]);
        record.CRSArrTime = fieldSetFlags()[7] ? this.CRSArrTime : (java.lang.Long) defaultValue(fields()[7]);
        record.UniqueCarrier = fieldSetFlags()[8] ? this.UniqueCarrier : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.FlightNum = fieldSetFlags()[9] ? this.FlightNum : (java.lang.Long) defaultValue(fields()[9]);
        record.TailNum = fieldSetFlags()[10] ? this.TailNum : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.ActualElapsedTime = fieldSetFlags()[11] ? this.ActualElapsedTime : (java.lang.Long) defaultValue(fields()[11]);
        record.CRSElapsedTime = fieldSetFlags()[12] ? this.CRSElapsedTime : (java.lang.Long) defaultValue(fields()[12]);
        record.AirTime = fieldSetFlags()[13] ? this.AirTime : (java.lang.Long) defaultValue(fields()[13]);
        record.ArrDelay = fieldSetFlags()[14] ? this.ArrDelay : (java.lang.Long) defaultValue(fields()[14]);
        record.DepDelay = fieldSetFlags()[15] ? this.DepDelay : (java.lang.Long) defaultValue(fields()[15]);
        record.Origin = fieldSetFlags()[16] ? this.Origin : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.Dest = fieldSetFlags()[17] ? this.Dest : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.Distance = fieldSetFlags()[18] ? this.Distance : (java.lang.Long) defaultValue(fields()[18]);
        record.TaxiIn = fieldSetFlags()[19] ? this.TaxiIn : (java.lang.Long) defaultValue(fields()[19]);
        record.TaxiOut = fieldSetFlags()[20] ? this.TaxiOut : (java.lang.Long) defaultValue(fields()[20]);
        record.Cancelled = fieldSetFlags()[21] ? this.Cancelled : (java.lang.Long) defaultValue(fields()[21]);
        record.CancellationCode = fieldSetFlags()[22] ? this.CancellationCode : (java.lang.CharSequence) defaultValue(fields()[22]);
        record.Diverted = fieldSetFlags()[23] ? this.Diverted : (java.lang.CharSequence) defaultValue(fields()[23]);
        record.CarrierDelay = fieldSetFlags()[24] ? this.CarrierDelay : (java.lang.CharSequence) defaultValue(fields()[24]);
        record.WeatherDelay = fieldSetFlags()[25] ? this.WeatherDelay : (java.lang.CharSequence) defaultValue(fields()[25]);
        record.NASDelay = fieldSetFlags()[26] ? this.NASDelay : (java.lang.CharSequence) defaultValue(fields()[26]);
        record.SecurityDelay = fieldSetFlags()[27] ? this.SecurityDelay : (java.lang.CharSequence) defaultValue(fields()[27]);
        record.LateAircraftDelay = fieldSetFlags()[28] ? this.LateAircraftDelay : (java.lang.CharSequence) defaultValue(fields()[28]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FlightDataAvroSchema>
    WRITER$ = (org.apache.avro.io.DatumWriter<FlightDataAvroSchema>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FlightDataAvroSchema>
    READER$ = (org.apache.avro.io.DatumReader<FlightDataAvroSchema>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
